version: '3.9'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=tpachato
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: chaimabf/tpachatproject-1.0.jar
    container_name: back
    restart: on-failure
    depends_on:
      - mysqldb
    ports:
      - '8089:8089'
    command: ["java","-jar","target/tpAchatProject-1.0.jar"]

    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/tpachato?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": null,
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    stdin_open: true
    tty: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db:



